name: DevSecOps CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # =============================
      # 1️⃣ Secrets Scanning - Gitleaks
      # =============================
      - name: Run Gitleaks (Secrets Scan)
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # =============================
      # 2️⃣ SAST - Semgrep
      # =============================
      - name: Run Semgrep (SAST)
        uses: returntocorp/semgrep-action@v1
        with:
          config: p/ci

      # =============================
      # 3️⃣ Build Java
      # =============================
      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: maven

      - name: Build (skip tests)
        run: mvn -DskipTests clean package

      # =============================
      # 4️⃣ Dependency Scan (Maven) - Stable mode
      # =============================
      - name: Download Dependency Check
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip curl
          VERSION=9.2.0
          curl -L --retry 5 --retry-delay 2 \
            -o dependency-check.zip \
            "https://github.com/jeremylong/DependencyCheck/releases/download/v${VERSION}/dependency-check-${VERSION}-release.zip"
          file dependency-check.zip
          unzip -q dependency-check.zip

      - name: Run Dependency Check (stable mode - no update)
        continue-on-error: true
        run: |
          ./dependency-check/bin/dependency-check.sh \
            --project "hapi-fhir" \
            --scan . \
            --format HTML \
            --out dependency-check-report \
            --noupdate

      - name: Upload Dependency Report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: dependency-check-report

      # =============================
      # 5️⃣ Build Docker Image
      # =============================
      - name: Build Docker image
        run: docker build -t hapi-fhir-jpaserver:ci .

      # =============================
      # 6️⃣ Install Trivy
      # =============================
      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget -qO trivy.deb https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.69.1_Linux-64bit.deb
          sudo dpkg -i trivy.deb

      # =============================
      # 7️⃣ Container Scan (fail if HIGH/CRITICAL)
      # =============================
      - name: Trivy scan (report only)
        run: |
          trivy image --scanners vuln --severity HIGH,CRITICAL hapi-fhir-jpaserver:ci
